name = "akernel_ping"
description = "akernel ping (ICMP echo over netserv ping sockets)"
version = "0.1.0-dev"

authors = ["Robert Roland"]
maintainers = ["Robert Roland <rob@retronauts.org>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
tags = []

project-files = ["ping.gpr"]
executables = ["ping.elf"]

[[depends-on]]
gnat_riscv64_elf = "*"
