name = "akernel_wait"
description = "akernel wait"
version = "0.1.0-dev"

authors = ["Robert Roland"]
maintainers = ["Robert Roland <rob@retronauts.org>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
tags = []

project-files = ["wait.gpr"]
executables = ["wait.elf"]

[[depends-on]]
gnat_riscv64_elf = "15.3.1"
