name = "akernel_info"
description = "akernel info"
version = "0.1.0-dev"

authors = ["Robert Roland"]
maintainers = ["Robert Roland <rob@retronauts.org>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
tags = []

project-files = ["info.gpr"]
executables = ["info.elf"]

[[depends-on]]
gnat_riscv64_elf = "15.3.1"
