name = "akernel_thread_test"
description = "akernel thread primitive smoke test"
version = "0.1.0-dev"

authors = ["Robert Roland"]
maintainers = ["Robert Roland <rob@retronauts.org>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
tags = []

project-files = ["thread_test.gpr"]
executables = ["thread_test.elf"]

[[depends-on]]
gnat_riscv64_elf = "15.3.1"

[[pins]]
gnat_riscv64_elf = { version='15.3.1' }
