name = "akernel_type"
description = "akernel Type command (milestone 32)"
version = "0.1.0-dev"

authors = ["Robert Roland"]
maintainers = ["Robert Roland <rob@retronauts.org>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
tags = []

project-files = ["type_util.gpr"]
executables = ["type.elf"]

[[depends-on]]
gnat_riscv64_elf = "*"
